'use client'
import { SessionProvider } from 'next-auth/react'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <SessionProvider basePath='api/auth'>{children}</SessionProvider>
      </body>
    </html>
  )
}
